apiVersion: operator.kyma-project.io/v1alpha1
kind: ModuleTemplate
metadata:
  name: replace-me
  namespace: default
  labels:
    "operator.kyma-project.io/managed-by": lifecycle-manager
    "operator.kyma-project.io/controller-name": "manifest"
    "operator.kyma-project.io/module-name": "replace-me"
    "operator.kyma-project.io/profile": "production"
  annotations:
    "operator.kyma-project.io/module-version": "v0.0.48"
    "operator.kyma-project.io/module-provider": "internal"
    "operator.kyma-project.io/descriptor-schema-version": "v2"
    "operator.kyma-project.io/generated-at": "2022-07-11T14:59:43Z"
spec:
  channel: stable
  target: remote
  data:
    kind: SKRModule
    resource: skrmodules
    apiVersion: operator.kyma-project.io/v1alpha1
    spec:
      initKey: initValue
  descriptor:
    component:
      componentReferences: []
      name: kyma-project.io/module/manifest1
      provider: internal
      repositoryContexts:
        - baseUrl: ghcr.io/ruanxin
          componentNameMapping: urlPath
          type: ociRegistry
        - baseUrl: ghcr.io/ruanxin/signed
          componentNameMapping: urlPath
          type: ociRegistry
      resources:
        - access:
            digest: sha256:9d37fb366e4371b44c94496f3db276bd6f3a1019c9d44077b689c68ec6486c1e
            type: localOciBlob
          digest:
            hashAlgorithm: sha256
            normalisationAlgorithm: genericBlobDigest/v1
            value: 9d37fb366e4371b44c94496f3db276bd6f3a1019c9d44077b689c68ec6486c1e
          name: config
          relation: local
          type: yaml
          version: v0.0.63
        - access:
            digest: sha256:2c329b6ff7379d94a009cd039aa38e23c18e4cd720526caaa44244d80f4ca989
            type: localOciBlob
          digest:
            hashAlgorithm: sha256
            normalisationAlgorithm: genericBlobDigest/v1
            value: 2c329b6ff7379d94a009cd039aa38e23c18e4cd720526caaa44244d80f4ca989
          name: crds
          relation: local
          type: crds
          version: v0.0.63
        - access:
            digest: sha256:12c75ae33ea65dd49247564af35ab048c95dfb8ca503799a295c2f5d02febec6
            type: localOciBlob
          digest:
            hashAlgorithm: sha256
            normalisationAlgorithm: genericBlobDigest/v1
            value: 12c75ae33ea65dd49247564af35ab048c95dfb8ca503799a295c2f5d02febec6
          name: kyma-load-test
          relation: local
          type: helm-chart
          version: v0.0.63
      sources: [ ]
      version: v0.0.63
    meta:
      schemaVersion: v2
    signatures: []
    
